name: production
protection_rules:
  - required_reviewers:
      required_approving_review_count: 2
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
  - wait_timer:
      wait_timer: 10
  - deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false
      allowed_branches:
        - main
  - required_status_checks:
      strict: true
      contexts:
        - "Database Migration Pipeline"
        - "Build and Test"
