name: staging
protection_rules:
  - required_reviewers:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
  - wait_timer:
      wait_timer: 5
  - deployment_branch_policy:
      protected_branches: false
      custom_branch_policies: true
      allowed_branches:
        - main
        - develop
        - feature/*
        - hotfix/*
        - release/*
