-- CreateTable
CREATE TABLE "public"."Order" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "mobile" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "pincode" TEXT NOT NULL,
    "courier_service" TEXT NOT NULL,
    "pickup_location" TEXT NOT NULL,
    "package_value" DOUBLE PRECISION NOT NULL,
    "weight" DOUBLE PRECISION NOT NULL,
    "total_items" INTEGER NOT NULL,
    "tracking_id" TEXT,
    "reference_number" TEXT,
    "is_cod" BOOLEAN NOT NULL DEFAULT false,
    "cod_amount" DOUBLE PRECISION,
    "reseller_name" TEXT,
    "reseller_mobile" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "delhivery_waybill_number" TEXT,
    "delhivery_order_id" TEXT,
    "delhivery_api_status" TEXT,
    "delhivery_api_error" TEXT,
    "delhivery_retry_count" INTEGER NOT NULL DEFAULT 0,
    "last_delhivery_attempt" TIMESTAMP(3),
    "shipment_length" DOUBLE PRECISION,
    "shipment_breadth" DOUBLE PRECISION,
    "shipment_height" DOUBLE PRECISION,
    "product_description" TEXT,
    "return_address" TEXT,
    "return_pincode" TEXT,
    "fragile_shipment" BOOLEAN NOT NULL DEFAULT false,
    "seller_name" TEXT,
    "seller_address" TEXT,
    "seller_gst" TEXT,
    "invoice_number" TEXT,
    "commodity_value" DOUBLE PRECISION,
    "tax_value" DOUBLE PRECISION,
    "category_of_goods" TEXT,
    "vendor_pickup_location" TEXT,
    "hsn_code" TEXT,
    "seller_cst_no" TEXT,
    "seller_tin" TEXT,
    "invoice_date" TEXT,
    "return_reason" TEXT,
    "ewbn" TEXT,

    CONSTRAINT "Order_pkey" PRIMARY KEY ("id")
);
